In [25]:
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

In [26]:
house_prices = pd.read_csv("data.csv")
house_prices.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [27]:
house_prices.drop(columns=["date", "street", "city", "statezip", "country"], inplace=True)
house_prices.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
0,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005
1,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0
2,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0
3,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0
4,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992

In [28]:
X = house_prices.drop(columns="price")
X.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005
1,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0
2,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0
3,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0
4,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992

In [29]:
y = house_prices.loc[:, "price"]
y.head()

0     313000.0
1    2384000.0
2     342000.0
3     420000.0
4     550000.0
Name: price, dtype: float64

In [55]:
price_prediction = tf.keras.models.Sequential([
    tf.keras.Input(shape=12, name="Input layer"),
    tf.keras.layers.Dense(units=6, activation=tf.keras.activations.linear, name="layer2"),
    tf.keras.layers.Dense(units=24, activation=tf.keras.activations.linear, name="layer3"),
    tf.keras.layers.Dense(units=1, name="Output")
])

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, train_size=0.8, shuffle=True, random_state=9)

In [56]:
price_prediction.compile(loss=tf.keras.losses.MeanAbsoluteError(), optimizer="adam")
price_prediction.fit(X_train, y_train)

115/115 [==============================] - 1s 2ms/step - loss: 543201.0625

In [33]:
y_test.shape

(920,)

In [57]:
y_pred = price_prediction.predict(X_test)

29/29 [==============================] - 0s 1ms/step

In [58]:
y_pred

array([[  50824.016 ],
       [   9939.762 ],
       [ 293897.12  ],
       [  18511.791 ],
       [  29453.2   ],
       [  30587.713 ],
       [  28363.783 ],
       [   9479.468 ],
       [   9048.757 ],
       [  60533.977 ],
       [  34896.535 ],
       [  16984.1   ],
       [  34518.934 ],
       [  29679.27  ],
       [  26721.354 ],
       [  30923.078 ],
       [  21504.967 ],
       [  25816.346 ],
       [  52962.676 ],
       [  21518.252 ],
       [  24822.36  ],
       [  55169.277 ],
       [  14443.128 ],
       [  27980.762 ],
       [ 310179.44  ],
       [  26476.822 ],
       [  24013.865 ],
       [  18437.568 ],
       [  40812.965 ],
       [  24382.791 ],
       [  23742.95  ],
       [  31485.61  ],
       [  22610.178 ],
       [  28262.818 ],
       [  27388.443 ],
       [  45572.836 ],
       [  21941.725 ],
       [  24997.396 ],
       [  95269.055 ],
       [ 107761.23  ],
       [  40421.785 ],
       [  46057.72  ],
       [   9273.115 ],
       [  10532.193 ],
       [  22017.127 ],
       [  18991.256 ],
       [ 746872.8   ],
       [  10439.296 ],
       [  11604.756 ],
       [  37655.45  ],
       [  21524.076 ],
       [  24713.133 ],
       [  29217.146 ],
       [  72463.68  ],
       [  37330.62  ],
       [  39197.492 ],
       [  18827.188 ],
       [  41138.75  ],
       [  12213.413 ],
       [  19912.154 ],
       [  32507.74  ],
       [  25780.643 ],
       [  45220.22  ],
       [  25166.432 ],
       [  20962.424 ],
       [ 192771.17  ],
       [  25139.145 ],
       [  32180.463 ],
       [  18573.412 ],
       [  23711.967 ],
       [  15408.823 ],
       [  24924.822 ],
       [  23549.447 ],
       [  19145.156 ],
       [  77557.18  ],
       [  28908.432 ],
       [  26406.768 ],
       [  22296.139 ],
       [  31964.623 ],
       [  53110.43  ],
       [  21932.441 ],
       [  37805.418 ],
       [  21104.674 ],
       [  27666.959 ],
       [  43893.766 ],
       [  27432.697 ],
       [  31640.242 ],
       [  50987.38  ],
       [  26473.627 ],
       [  46433.996 ],
       [  19578.008 ],
       [  27440.174 ],
       [  39025.582 ],
       [  47143.883 ],
       [  19716.953 ],
       [  28434.322 ],
       [  15975.018 ],
       [  93672.484 ],
       [  34817.36  ],
       [  24025.49  ],
       [  14747.824 ],
       [  34163.477 ],
       [  16842.121 ],
       [   8114.725 ],
       [  26407.404 ],
       [  38288.67  ],
       [  30404.598 ],
       [  22425.72  ],
       [  96220.31  ],
       [  35595.76  ],
       [   8784.735 ],
       [  25608.822 ],
       [  24927.639 ],
       [  26822.953 ],
       [  24912.043 ],
       [  92715.766 ],
       [  14481.86  ],
       [  29205.504 ],
       [  90275.04  ],
       [  22701.729 ],
       [  19091.295 ],
       [  29100.926 ],
       [  27597.514 ],
       [  34232.69  ],
       [  22686.164 ],
       [  32313.236 ],
       [  19820.705 ],
       [ 117484.164 ],
       [  25487.68  ],
       [  21944.738 ],
       [  15874.23  ],
       [  15990.019 ],
       [  39177.07  ],
       [  28597.246 ],
       [  27177.584 ],
       [  32714.432 ],
       [  13979.435 ],
       [  16695.553 ],
       [  16075.006 ],
       [  19628.459 ],
       [  16358.51  ],
       [ 320917.25  ],
       [  23417.475 ],
       [  13749.001 ],
       [  74358.1   ],
       [  38724.246 ],
       [  11329.795 ],
       [  28853.209 ],
       [   9454.906 ],
       [  36945.87  ],
       [  97866.52  ],
       [  22115.287 ],
       [ 370974.12  ],
       [ 156047.67  ],
       [ 205739.19  ],
       [  19297.166 ],
       [ 135938.17  ],
       [  34177.633 ],
       [  19422.98  ],
       [  25686.357 ],
       [  25621.182 ],
       [  23202.799 ],
       [  32437.771 ],
       [  36190.43  ],
       [  22380.998 ],
       [  49465.41  ],
       [  17853.926 ],
       [  11826.931 ],
       [  17119.389 ],
       [  24121.732 ],
       [  53394.035 ],
       [  23387.951 ],
       [  30008.623 ],
       [  20271.193 ],
       [  72915.41  ],
       [  18873.53  ],
       [   7479.6577],
       [  34918.31  ],
       [  23464.084 ],
       [  31210.889 ],
       [  25299.283 ],
       [   8864.419 ],
       [  23354.586 ],
       [  10412.858 ],
       [  62963.14  ],
       [  24019.562 ],
       [  26147.84  ],
       [   9426.353 ],
       [  27680.81  ],
       [  27932.87  ],
       [  25026.291 ],
       [ 149483.27  ],
       [  62348.535 ],
       [  17676.3   ],
       [  23883.525 ],
       [ 106532.51  ],
       [  29008.916 ],
       [  29674.049 ],
       [  28237.43  ],
       [  17622.553 ],
       [  64450.316 ],
       [  25263.744 ],
       [  27382.062 ],
       [  32812.18  ],
       [  51157.684 ],
       [  31563.264 ],
       [  10251.259 ],
       [   9157.687 ],
       [  18656.645 ],
       [  67338.086 ],
       [   9022.31  ],
       [  25110.365 ],
       [   9818.725 ],
       [  28531.822 ],
       [  34459.01  ],
       [  55391.254 ],
       [  42494.79  ],
       [  20202.229 ],
       [  29405.08  ],
       [  30385.74  ],
       [  21053.83  ],
       [  14627.481 ],
       [  39460.63  ],
       [  17007.842 ],
       [  31440.482 ],
       [  32724.273 ],
       [  13917.495 ],
       [  34180.105 ],
       [  29335.936 ],
       [  15596.2705],
       [  26115.998 ],
       [   8995.411 ],
       [  22507.559 ],
       [  25740.146 ],
       [  31446.447 ],
       [  33372.3   ],
       [  26806.545 ],
       [ 442470.72  ],
       [  23495.393 ],
       [ 116932.24  ],
       [  37311.676 ],
       [  64596.902 ],
       [  48269.438 ],
       [  25719.969 ],
       [  13276.21  ],
       [  35911.96  ],
       [  17447.17  ],
       [  37076.94  ],
       [  66928.81  ],
       [  24755.717 ],
       [  89595.836 ],
       [  22425.727 ],
       [  11640.289 ],
       [  31046.205 ],
       [  26237.52  ],
       [  37101.22  ],
       [  10359.107 ],
       [  20275.172 ],
       [  20219.297 ],
       [  53929.625 ],
       [  25101.428 ],
       [  22421.28  ],
       [  29079.318 ],
       [  10302.182 ],
       [  20187.87  ],
       [  24052.281 ],
       [  26826.863 ],
       [  70324.48  ],
       [  34780.957 ],
       [  24483.63  ],
       [  33697.19  ],
       [  24735.162 ],
       [  22370.63  ],
       [  28777.9   ],
       [  24751.553 ],
       [  20445.469 ],
       [  46654.277 ],
       [  29035.83  ],
       [  28053.674 ],
       [  24049.834 ],
       [  33185.316 ],
       [  17130.607 ],
       [  18319.15  ],
       [  22922.639 ],
       [  25857.664 ],
       [  27274.348 ],
       [  29226.088 ],
       [  89275.65  ],
       [  24791.348 ],
       [  17720.031 ],
       [  50798.938 ],
       [  50686.875 ],
       [  31743.123 ],
       [  94022.48  ],
       [  11555.733 ],
       [  53370.26  ],
       [  54263.207 ],
       [  16516.543 ],
       [  16100.373 ],
       [  19291.459 ],
       [  11279.856 ],
       [1456393.8   ],
       [  29225.566 ],
       [  16670.336 ],
       [  20242.055 ],
       [  46488.473 ],
       [  22554.521 ],
       [  28625.238 ],
       [  21354.486 ],
       [  57959.51  ],
       [  24093.81  ],
       [  59642.684 ],
       [  27752.912 ],
       [  26672.438 ],
       [  16524.613 ],
       [  29254.762 ],
       [  28461.83  ],
       [  39727.895 ],
       [  16175.22  ],
       [  22576.201 ],
       [ 103148.62  ],
       [  26247.328 ],
       [   9419.893 ],
       [  17992.342 ],
       [  91908.74  ],
       [  17804.117 ],
       [  48902.473 ],
       [  30701.285 ],
       [  23186.7   ],
       [  32062.488 ],
       [  14038.372 ],
       [  25895.506 ],
       [  27413.191 ],
       [  27055.045 ],
       [  43872.734 ],
       [  17820.604 ],
       [  34527.207 ],
       [ 141958.89  ],
       [  41287.094 ],
       [  88652.    ],
       [  14102.184 ],
       [  18571.73  ],
       [  29660.777 ],
       [  36194.23  ],
       [  18634.191 ],
       [  14621.299 ],
       [  26890.191 ],
       [  28661.35  ],
       [  20723.715 ],
       [  23659.477 ],
       [  24541.305 ],
       [  16408.895 ],
       [  31197.365 ],
       [  29484.873 ],
       [  92974.055 ],
       [  22102.576 ],
       [  62342.426 ],
       [  32252.328 ],
       [  28370.613 ],
       [  26876.615 ],
       [  23742.623 ],
       [  71093.43  ],
       [  15222.373 ],
       [  22016.043 ],
       [  26497.264 ],
       [ 184397.73  ],
       [  18867.375 ],
       [  18024.115 ],
       [  35674.87  ],
       [  24590.197 ],
       [  33967.883 ],
       [  20387.959 ],
       [  22233.586 ],
       [  84808.414 ],
       [  21596.748 ],
       [  11257.323 ],
       [  26779.824 ],
       [  34027.566 ],
       [  20269.48  ],
       [  32996.22  ],
       [  26189.424 ],
       [  18126.219 ],
       [  20261.248 ],
       [  49423.38  ],
       [  37234.996 ],
       [  31395.72  ],
       [  31894.613 ],
       [  17404.572 ],
       [  29277.248 ],
       [   8497.724 ],
       [  33798.656 ],
       [  43304.758 ],
       [  25640.592 ],
       [  25342.146 ],
       [  22444.396 ],
       [  64885.895 ],
       [  23861.258 ],
       [  30966.604 ],
       [  21861.998 ],
       [  31805.85  ],
       [  22239.863 ],
       [  30718.83  ],
       [  27157.676 ],
       [  26832.229 ],
       [  51732.95  ],
       [  21716.049 ],
       [ 146433.98  ],
       [  26726.81  ],
       [  16111.343 ],
       [  43263.38  ],
       [  13816.151 ],
       [  30736.46  ],
       [ 119306.76  ],
       [  17589.604 ],
       [  27881.26  ],
       [  21418.752 ],
       [  96979.125 ],
       [  22468.537 ],
       [  23247.271 ],
       [  30386.627 ],
       [ 109939.63  ],
       [  34364.535 ],
       [  31963.922 ],
       [  17803.121 ],
       [  53415.844 ],
       [  14783.573 ],
       [  28219.568 ],
       [  49617.97  ],
       [  34044.527 ],
       [  32761.42  ],
       [  31714.35  ],
       [  20618.506 ],
       [  14547.525 ],
       [  22016.002 ],
       [  19300.1   ],
       [  20163.344 ],
       [ 211967.64  ],
       [   9479.579 ],
       [  21382.055 ],
       [  19452.355 ],
       [  93763.57  ],
       [  29120.418 ],
       [  31293.623 ],
       [  17925.775 ],
       [  31634.732 ],
       [  20074.232 ],
       [ 992920.5   ],
       [  27998.318 ],
       [  24863.4   ],
       [  17636.627 ],
       [  22966.441 ],
       [  14877.921 ],
       [  24840.107 ],
       [ 544354.7   ],
       [  22712.615 ],
       [  24589.99  ],
       [  24440.076 ],
       [  28666.44  ],
       [  28277.795 ],
       [  17167.89  ],
       [ 232601.56  ],
       [  22055.764 ],
       [  32851.51  ],
       [  24841.258 ],
       [  23110.018 ],
       [  49038.34  ],
       [  47531.582 ],
       [  13500.238 ],
       [  24793.867 ],
       [  23463.73  ],
       [  10081.218 ],
       [  56024.84  ],
       [  50506.543 ],
       [  29602.086 ],
       [ 121312.664 ],
       [  19914.025 ],
       [  28151.166 ],
       [  27850.645 ],
       [   8630.882 ],
       [  25432.229 ],
       [  27785.395 ],
       [ 112877.305 ],
       [  24070.514 ],
       [  36939.496 ],
       [  33326.44  ],
       [  47615.81  ],
       [  27945.686 ],
       [   9387.553 ],
       [  25906.74  ],
       [  19574.531 ],
       [  40415.793 ],
       [  24800.525 ],
       [  44098.47  ],
       [  36624.426 ],
       [  17006.764 ],
       [  91276.72  ],
       [  24825.693 ],
       [  17911.996 ],
       [  20201.867 ],
       [  16228.46  ],
       [  32002.41  ],
       [  21967.459 ],
       [  25077.6   ],
       [  10377.424 ],
       [  21455.564 ],
       [  50758.867 ],
       [  29780.049 ],
       [   8622.862 ],
       [ 172964.62  ],
       [  25679.207 ],
       [   8987.423 ],
       [  23530.412 ],
       [  23961.373 ],
       [  36831.24  ],
       [  92599.63  ],
       [  29638.896 ],
       [  25845.674 ],
       [  25579.2   ],
       [  44392.426 ],
       [  24884.576 ],
       [  35462.004 ],
       [ 155826.86  ],
       [  25948.096 ],
       [  25606.738 ],
       [  27251.61  ],
       [  10349.6045],
       [  81908.19  ],
       [ 118493.41  ],
       [  22802.248 ],
       [  30325.854 ],
       [   9733.108 ],
       [  28198.135 ],
       [  28357.982 ],
       [  23218.85  ],
       [  25125.342 ],
       [  22709.744 ],
       [  34931.44  ],
       [  16648.951 ],
       [  17715.057 ],
       [  28050.656 ],
       [  12907.096 ],
       [  41130.04  ],
       [  23559.484 ],
       [  19401.562 ],
       [  35658.258 ],
       [  31035.695 ],
       [ 108652.664 ],
       [  60420.37  ],
       [  41033.78  ],
       [  30605.123 ],
       [  24521.285 ],
       [  30418.277 ],
       [  72765.05  ],
       [  28731.13  ],
       [  22839.885 ],
       [  17675.783 ],
       [  25585.31  ],
       [  22763.49  ],
       [  20337.111 ],
       [  19690.385 ],
       [  29750.219 ],
       [  31123.004 ],
       [  32519.566 ],
       [  46128.676 ],
       [  11592.651 ],
       [  40793.137 ],
       [  30034.646 ],
       [  25868.209 ],
       [ 148684.73  ],
       [  20654.586 ],
       [  22711.229 ],
       [  11833.83  ],
       [  64736.945 ],
       [  12992.154 ],
       [ 500622.12  ],
       [  17834.316 ],
       [  29704.166 ],
       [  31515.54  ],
       [  19471.205 ],
       [  22081.521 ],
       [  22136.592 ],
       [  25859.535 ],
       [  26832.12  ],
       [  51503.473 ],
       [  67598.43  ],
       [  45645.26  ],
       [  62135.78  ],
       [  29064.592 ],
       [  27749.945 ],
       [  26167.322 ],
       [  27312.328 ],
       [  18458.617 ],
       [   9686.958 ],
       [  23473.215 ],
       [  11180.089 ],
       [  30324.219 ],
       [  84118.26  ],
       [  33789.45  ],
       [  20915.53  ],
       [  86076.86  ],
       [  24221.115 ],
       [  19952.215 ],
       [  27426.447 ],
       [ 125692.4   ],
       [   9399.538 ],
       [  18795.252 ],
       [  32271.2   ],
       [  24799.51  ],
       [  22527.877 ],
       [  14266.202 ],
       [  13870.645 ],
       [  35223.996 ],
       [  26232.125 ],
       [  37809.12  ],
       [ 144764.05  ],
       [  16424.154 ],
       [  20570.629 ],
       [  35366.137 ],
       [  25724.732 ],
       [  27646.404 ],
       [  27219.37  ],
       [  34133.81  ],
       [  24994.96  ],
       [  22289.928 ],
       [  27441.39  ],
       [  10066.22  ],
       [  30370.621 ],
       [  36417.59  ],
       [  14084.682 ],
       [  99317.71  ],
       [  29352.443 ],
       [  26556.762 ],
       [  23995.03  ],
       [  94629.11  ],
       [  67288.4   ],
       [ 101840.37  ],
       [   7736.8926],
       [  28204.463 ],
       [  33143.625 ],
       [  29068.842 ],
       [ 697966.25  ],
       [   8298.302 ],
       [  33675.695 ],
       [  24374.36  ],
       [  53628.29  ],
       [  23626.943 ],
       [  16476.822 ],
       [  22525.057 ],
       [  36343.71  ],
       [ 111165.4   ],
       [  22986.713 ],
       [   8244.831 ],
       [ 506412.22  ],
       [  12303.903 ],
       [ 474550.06  ],
       [  42195.332 ],
       [  30814.732 ],
       [  33942.418 ],
       [  26821.549 ],
       [  24240.236 ],
       [  21246.418 ],
       [  31003.025 ],
       [  20747.443 ],
       [  19830.697 ],
       [  28852.74  ],
       [  87641.086 ],
       [  20483.963 ],
       [  26041.729 ],
       [  19852.896 ],
       [  27818.896 ],
       [  57276.082 ],
       [  27650.07  ],
       [  44601.26  ],
       [  23239.463 ],
       [   8983.12  ],
       [ 129286.24  ],
       [  35013.81  ],
       [  21479.13  ],
       [  27422.502 ],
       [  27241.295 ],
       [  17338.61  ],
       [  16503.447 ],
       [  42413.434 ],
       [  27120.275 ],
       [  19641.053 ],
       [  16592.021 ],
       [  28341.812 ],
       [  29060.373 ],
       [ 143245.39  ],
       [  25957.057 ],
       [  21536.729 ],
       [  25480.346 ],
       [  15760.624 ],
       [  21347.96  ],
       [  28604.143 ],
       [  18579.861 ],
       [   9328.752 ],
       [ 116065.74  ],
       [  18887.145 ],
       [  24326.92  ],
       [  32842.438 ],
       [  65590.805 ],
       [  21630.807 ],
       [  45520.246 ],
       [  18659.693 ],
       [  34510.996 ],
       [  20611.34  ],
       [  44674.67  ],
       [  23593.771 ],
       [  29626.732 ],
       [  27515.566 ],
       [  24309.207 ],
       [  19017.633 ],
       [  17588.037 ],
       [  29441.035 ],
       [  31576.404 ],
       [  20182.04  ],
       [  17391.338 ],
       [  45630.332 ],
       [  10686.157 ],
       [  28467.982 ],
       [  35389.164 ],
       [  52160.49  ],
       [  23495.82  ],
       [  91258.43  ],
       [  24144.916 ],
       [ 111563.4   ],
       [   8474.933 ],
       [  26830.553 ],
       [  21259.771 ],
       [  24434.166 ],
       [  23896.951 ],
       [  88646.67  ],
       [  82388.055 ],
       [  26838.13  ],
       [  26230.186 ],
       [  30200.023 ],
       [  16275.351 ],
       [  19144.66  ],
       [  21932.178 ],
       [  34184.176 ],
       [  39803.043 ],
       [  47586.168 ],
       [  32372.508 ],
       [  95758.49  ],
       [  26130.041 ],
       [  22217.535 ],
       [   9958.731 ],
       [  26592.521 ],
       [  37894.79  ],
       [  11120.5205],
       [  23021.963 ],
       [  12680.184 ],
       [  24889.629 ],
       [  25978.365 ],
       [  27258.338 ],
       [  22459.193 ],
       [  34121.652 ],
       [  20537.824 ],
       [  25284.203 ],
       [  19048.457 ],
       [  11143.653 ],
       [  32757.857 ],
       [  19885.428 ],
       [  48868.457 ],
       [  67478.4   ],
       [  19760.172 ],
       [  20629.404 ],
       [  24702.639 ],
       [ 403202.1   ],
       [  19168.928 ],
       [  19896.414 ],
       [  14844.298 ],
       [  39955.992 ],
       [   9191.233 ],
       [  17233.438 ],
       [  26199.186 ],
       [  52911.816 ],
       [  23586.674 ],
       [  19113.74  ],
       [  51108.15  ],
       [  25509.896 ],
       [  34534.734 ],
       [  27642.852 ],
       [  77540.164 ],
       [  33612.37  ],
       [  28656.527 ],
       [  17134.162 ],
       [  19220.738 ],
       [  27153.252 ],
       [  13333.865 ],
       [  26387.578 ],
       [  38264.94  ],
       [ 154797.05  ],
       [  26237.104 ],
       [  26932.08  ],
       [  23370.385 ],
       [  99203.49  ],
       [  74565.51  ],
       [  17742.703 ],
       [  31112.215 ],
       [  30396.998 ],
       [  20459.275 ],
       [  15589.522 ],
       [  18908.365 ],
       [  25990.572 ],
       [  20257.408 ],
       [  23956.041 ],
       [  17582.627 ],
       [  16189.532 ],
       [  31810.682 ],
       [  42175.31  ],
       [  22426.762 ],
       [  26231.723 ],
       [  24689.916 ],
       [  27558.025 ],
       [  91081.63  ],
       [  18837.441 ],
       [  67981.6   ],
       [  43445.477 ],
       [  19422.139 ],
       [  25680.064 ],
       [  36037.215 ],
       [  11273.144 ],
       [  98151.94  ],
       [  69082.13  ],
       [  27570.959 ],
       [  18162.32  ],
       [  25797.693 ],
       [  29455.129 ],
       [  17691.994 ],
       [  16768.334 ],
       [  24212.9   ],
       [  25426.834 ],
       [  19951.979 ],
       [  55832.996 ],
       [ 216857.2   ],
       [  38840.035 ],
       [  22727.104 ],
       [  19106.604 ],
       [  27379.463 ],
       [  27913.717 ],
       [  26571.729 ],
       [  18552.045 ],
       [  17831.025 ],
       [  18256.637 ],
       [  22033.186 ],
       [  20126.398 ],
       [  27807.885 ],
       [  28664.836 ],
       [  19105.955 ],
       [  26469.012 ],
       [ 109043.35  ],
       [  20205.975 ],
       [  32532.13  ],
       [  18916.975 ],
       [  24294.982 ],
       [  19930.748 ],
       [  32328.416 ],
       [  28833.71  ],
       [  18656.72  ],
       [  39289.312 ],
       [  18826.953 ],
       [  24921.045 ],
       [  24944.285 ],
       [  35410.074 ],
       [  34573.21  ],
       [  16532.553 ],
       [  29180.713 ],

In [59]:
price_prediction.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 layer2 (Dense)              (None, 6)                 78

 layer3 (Dense)              (None, 24)                168

 Output (Dense)              (None, 1)                 25

=================================================================
Total params: 271
Trainable params: 271
Non-trainable params: 0
_________________________________________________________________

In [60]:
test = [[3.0, 1.50, 1340, 7912, 1.5, 0, 0, 3, 1340, 0, 1955, 2005]]
price_prediction.predict(test)

1/1 [==============================] - 0s 59ms/step

array([[27035.74]], dtype=float32)

In [62]:
price_prediction.evaluate(X_test, y_test)

29/29 [==============================] - 0s 1ms/step - loss: 487752.6875

487752.6875

In [63]:
type(price_prediction)

keras.engine.sequential.Sequential

In [64]:
price_prediction.weights

[<tf.Variable 'layer2/kernel:0' shape=(12, 6) dtype=float32, numpy=
 array([[ 3.0666524e-01, -4.9989828e-01, -6.8678044e-02, -2.1387851e-01,
          1.1993369e-01,  3.9881170e-01],
        [ 4.7567278e-01,  3.1370264e-01, -3.9702572e-02,  6.5884960e-01,
          1.7496482e-01,  5.7255912e-01],
        [ 4.9953040e-01,  4.9092188e-01,  3.1559047e-01,  6.8953180e-01,
          2.5774500e-01,  3.3602592e-02],
        [ 6.9585487e-02,  2.0408745e-01,  4.7699246e-01,  6.6876370e-01,
         -3.9683855e-01,  6.4670563e-01],
        [ 5.8931403e-02,  4.7147149e-01,  1.3678744e-01,  6.9687784e-01,
         -6.4564100e-04,  2.0528890e-01],
        [ 1.0190048e-01, -2.9774821e-01, -8.0211386e-02, -2.0202637e-01,
          3.4503600e-01,  1.6514459e-01],
        [-3.9420044e-01, -9.5732257e-02,  5.8768857e-01,  9.5698386e-02,
          1.3046135e-01,  4.5799541e-01],
        [ 2.9191679e-01, -1.9198155e-03, -3.1520286e-01,  3.7698835e-01,
         -3.8904530e-01,  2.4461865e-02],
        [ 3.0383134e-01,  3.7601313e-01,  2.2114198e-01, -3.1886050e-01,
         -4.9439859e-01, -6.7667693e-02],
        [ 3.4904319e-01, -5.6864887e-02,  2.8076792e-01, -3.2853392e-01,
          2.7185026e-01,  2.9283714e-02],
        [ 4.3505824e-01, -1.0553661e-01,  6.9933736e-01,  3.2810561e-02,
          3.2445300e-01,  7.2459239e-01],
        [ 4.8852310e-01, -9.0335429e-02,  6.1773407e-01,  9.1548346e-02,
         -5.6243151e-01, -6.3289911e-02]], dtype=float32)>,
 <tf.Variable 'layer2/bias:0' shape=(6,) dtype=float32, numpy=
 array([ 0.14129224,  0.05510103,  0.12271009,  0.15614326, -0.02890888,
         0.15037659], dtype=float32)>,
 <tf.Variable 'layer3/kernel:0' shape=(6, 24) dtype=float32, numpy=
 array([[ 0.3900092 , -0.09590055,  0.0053234 ,  0.23614648,  0.18486613,
          0.36153492, -0.01649891, -0.05047546, -0.24298665, -0.40047497,
         -0.27315652, -0.02230874,  0.56359017, -0.41934326, -0.25280815,
          0.13207644, -0.20852084, -0.5114098 , -0.21872926,  0.27394578,
          0.5762347 , -0.10401916,  0.11446945, -0.4630204 ],
        [-0.2034538 , -0.19186325,  0.08324452, -0.12098702,  0.41768122,
          0.10894484, -0.30178916,  0.17708062, -0.4148601 , -0.06868449,
         -0.16766587, -0.05254328,  0.4490238 , -0.06049649,  0.23939398,
         -0.2251038 , -0.36117986,  0.32707185, -0.22710633,  0.55945295,
         -0.15831646,  0.4029654 ,  0.04080426,  0.01611014],
        [ 0.02770474, -0.21368879,  0.5058906 ,  0.17363977, -0.2713872 ,
         -0.05486555, -0.46191248, -0.15874769,  0.1292799 , -0.3726306 ,
          0.565522  ,  0.12833536, -0.19687647,  0.28397104, -0.00555166,
         -0.04565017, -0.24318515,  0.2690136 , -0.10682803,  0.14526436,
          0.50621504,  0.08449604, -0.05613287, -0.07421578],
        [ 0.39098528,  0.0992343 ,  0.3547622 , -0.21036918,  0.4364497 ,
          0.14290334,  0.11239923, -0.14766389, -0.248294  , -0.37874448,
         -0.07624485, -0.35029665,  0.3441337 ,  0.3213223 , -0.41792607,
          0.23310277, -0.5005836 ,  0.17638499, -0.01371673, -0.09124073,
          0.38232675,  0.08164968, -0.24538699, -0.34280583],
        [ 0.2813777 ,  0.11756635, -0.43641248,  0.42589173, -0.2063157 ,
          0.2977618 ,  0.44416153, -0.42043096,  0.08482915,  0.02835697,
         -0.14775848,  0.3234418 ,  0.16331422, -0.2911894 , -0.25705072,
          0.0240148 , -0.18729776, -0.16180758, -0.25038227, -0.16245578,
         -0.44051152,  0.17085068, -0.23243102,  0.41107875],
        [-0.07292419, -0.1278053 , -0.05855395, -0.34034398,  0.27012545,
          0.04140807, -0.52989507, -0.21218416, -0.12629981, -0.20162724,
          0.06446138,  0.09937719, -0.23608251, -0.39705098, -0.5234076 ,
         -0.21786913, -0.37219   , -0.02577101,  0.26739487,  0.43772036,
          0.09128878,  0.07201556,  0.50999403, -0.42356318]],
       dtype=float32)>,
 <tf.Variable 'layer3/bias:0' shape=(24,) dtype=float32, numpy=
 array([ 0.11229917, -0.01330242,  0.11981185, -0.12254913,  0.13545999,
         0.11025056, -0.12204237,  0.10739075, -0.08170062, -0.11990219,
         0.12114117,  0.07824587,  0.11062735, -0.10568078, -0.12216508,
        -0.08245673, -0.12248447, -0.10722902, -0.09477621,  0.13823816,
         0.12876634,  0.10883208,  0.12012605, -0.15850918], dtype=float32)>,
 <tf.Variable 'Output/kernel:0' shape=(24, 1) dtype=float32, numpy=
 array([[ 0.30775937],
        [-0.06145645],
        [ 0.52162623],
        [-0.34857097],
        [ 0.19188254],
        [ 0.3049828 ],
        [-0.3831771 ],
        [ 0.2474213 ],
        [-0.10282577],
        [-0.5407713 ],
        [ 0.50749916],
        [ 0.00239569],
        [ 0.31809726],
        [-0.1690648 ],
        [-0.42048928],
        [-0.03025642],
        [-0.38014334],
        [-0.22391406],
        [-0.05229247],
        [ 0.18473816],
        [ 0.24347152],
        [ 0.13467816],
        [ 0.4069248 ],
        [-0.12524047]], dtype=float32)>,
 <tf.Variable 'Output/bias:0' shape=(1,) dtype=float32, numpy=array([0.1145201], dtype=float32)>]